=== glpo/ASRGateway/gateway/target/classes/xml/ASRValidationConfiguration.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="operationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="in" />
			<xs:enumeration value="not in" />
			<xs:enumeration value="empty" />
			<xs:enumeration value="not empty" />
			<xs:enumeration value="equals" />
			<xs:enumeration value="not equals" />
			<xs:enumeration value="eq" />
			<xs:enumeration value="lt" />
			<xs:enumeration value="gt" />
			<xs:enumeration value="le" />
			<xs:enumeration value="ge" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="kindType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="name" />
			<xs:enumeration value="one" />
			<xs:enumeration value="all" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="idType">
		<xs:restriction base="xs:string" />		
	</xs:simpleType>

	<xs:simpleType name="formNameType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ASR" />
			<xs:enumeration value="Trunking" />
			<xs:enumeration value="Transport" />
			<xs:enumeration value="EUSA" />
			<xs:enumeration value="FGA" />
			<xs:enumeration value="Ring" />
			<xs:enumeration value="WAL" />
			<xs:enumeration value="ACI" />
			<xs:enumeration value="ARI" />
			<xs:enumeration value="NAI" />
			<xs:enumeration value="SALI" />
			<xs:enumeration value="MSL" />
			<xs:enumeration value="EOD" />
			<xs:enumeration value="EVC" />
			<xs:enumeration value="Multi EC" />
			<xs:enumeration value="VCAT" />
			<xs:enumeration value="TQ" />
			<xs:enumeration value="VC" />
			<xs:enumeration value="PC" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="attrType">
		<xs:sequence>
			<xs:element name="value" type="xs:string" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="idType" />
		<xs:attribute name="operator" type="operationType" />
		<xs:attribute name="start_pos" type="xs:positiveInteger" />
		<xs:attribute name="end_pos" type="xs:positiveInteger" />
		<xs:attribute name="kind" type="kindType" />
		<xs:attribute name="form" type="formNameType" />
	</xs:complexType>

	<xs:complexType name="otherwiseType">
		<xs:sequence />
	</xs:complexType>

	<xs:complexType name="optionalType">
		<xs:sequence>
			<xs:element name="attr" type="attrType" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="otherwise" type="otherwiseType"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="acceptable_valuesType">
		<xs:sequence>
			<xs:element name="value" type="xs:string" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="requiredAndProhibitedType">
		<xs:sequence>
			<xs:element name="acceptable_values" type="acceptable_valuesType"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="attr" type="attrType" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="otherwise" type="otherwiseType"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="error_message" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="idTagType">
		<xs:simpleContent>
			<xs:extension base="idType">
				<xs:attribute name="start_pos" type="xs:positiveInteger" />
				<xs:attribute name="end_pos" type="xs:positiveInteger" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="target_attributesType">
		<xs:sequence>
			<xs:element name="id" type="idTagType" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="additional_paramsType">
		<xs:sequence>
			<xs:any minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="validatorType">
		<xs:sequence>
			<xs:element name="target_attributes" type="target_attributesType"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="additional_params" type="additional_paramsType"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="required" type="requiredAndProhibitedType"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="optional" type="optionalType" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="prohibited" type="requiredAndProhibitedType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="class" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="formType">		
		<xs:sequence>
			<xs:element name="validator" type="validatorType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="formNameType" />
	</xs:complexType>

	<xs:complexType name="configurationType">
		<xs:sequence>
			<xs:element name="form" type="formType" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="configuration" type="configurationType" />
</xs:schema>

=== glpo/ASRGateway/gateway/src/main/resources/xml/ASRVC.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ASRValidationConfiguration.xsd">
<!-- Tables: 
		1. Access Change Request (ASR) Form validation rules 
		2. Trunking Form Validation Rules 
		3. End User Special Access (EUSA) Form Validation Rules 
		4. Transport Form Validation rules 
		5. WATS Access Line (WAL) Form Validation Rules 
		6. Ring Form Validation Rules 
		7. Feature Group A (FGA) From Validation rules 
        
        A1. Additional Circuit Information (ACI) Form validation rules 
        A2. Service Address Location Information (SALI) Form Validation Rules  - was fully reviewed on UATs by [vovo]
        A3. Translation Questionnaire (TQ) Form Validation Rules [09.12.13 reviewed]
        A4. End Office Details (EOD) Form Validation Rules 
        A5. Multiple Exchange Company (MULT_EC) Form Validation Rules 
        A6. Additional Ring Information (ARI) Form Validation Rules 
        A7. Virtual Concatenation (VCAT) Form Validation Rules 
        A8. Ethernet Virtual Connection (EVC) Form Validation Rules 
        A9. Virtual Connection (VC) Form Validation Rules 
		A10. Port Configuration (PC) Form Validation Rules 
        A11. Multipoint Service Legs (MSL) Form Validation Rules 
        A12. Network Assignment information (NAI) Form Validation Rules		
	-->

	<form name="ASR">
		<validator name="1_QA" class="com.glpo.gateway.oc.GenericParameterValidator">
			<target_attributes>
				<id>QA</id><!-- 1_QA -->
			</target_attributes>
			<optional>
				<attr id="ACT" operator="in"><!-- ACT - list type -->
					<value>N</value><!-- N -->
					<value>C</value><!-- C -->
					<value>T</value><!-- T -->
				</attr>
			</optional>
			<prohibited
				error_message="'${attr}' should not be filled on '${form}' cause &lt;br&gt; - the ACT filed is not in N, C or T.">
				<otherwise />
			</prohibited>
		</validator>

		<validator name="DDD" class="com.glpo.gateway.oc.GenericParameterValidator">
			<target_attributes>
				<id>DDD</id> <!-- DDD -->
			</target_attributes>

			<required error_message="'${attr}' is empty on ${form}">
				<attr id="DDD" operator="empty" /><!-- DDD -->
			</required>
		</validator>

		<validator name="1_FDT" class="com.glpo.gateway.oc.GenericParameterValidator">

			<target_attributes>
				<id>FDT</id> <!-- 1_FDT -->
			</target_attributes>

			<required error_message="'${attr}' should be filled on '${form}' cause &lt;br&gt; - the CB TEl NO filled.">
				<attr id="TEL NO" operator="not empty" /> <!-- CB TEL NO -->
			</required>

			<optional>
				<otherwise />
			</optional>

			<prohibited error_message="'${attr}' should not be filled on '${form}' cause &lt;br&gt; - ACT field is R.">
				<attr id="ACT" operator="in">	<!-- ACT - list type -->
					<value>R</value> <!-- R -->
				</attr>
			</prohibited>
		</validator>

		<validator name="1_PROJECT" class="com.glpo.gateway.oc.GenericParameterValidator">
			<target_attributes>
				<id>PROJECT</id> <!-- 1_PROJECT masked type -->
			</target_attributes>

			<required
				error_message="'${attr}' should be filled on '${form}' cause &lt;br&gt; - the ACT is N or D,
			&lt;br&gt; - the CCVN filled.">
				<attr id="ACT" operator="in"> <!-- ACT - list type -->
					<value>N</value><!-- N -->
					<value>D</value><!-- D -->
				</attr>

				<attr id="CCVN" operator="not empty" /><!-- CCVN -->
			</required>

			<optional>
				<otherwise />
			</optional>
		</validator>

		<validator name="1_CCI" class="com.glpo.gateway.oc.GenericParameterValidator">
			<target_attributes>
				<id>CCI</id> <!-- CCI - list type -->
			</target_attributes>

			<optional>
				<attr id="REQTYP" operator="in"> <!-- REQTYP (1) - list type -->
					<value>E</value> <!-- E -->
					<value>M</value> <!-- M -->
					<value>L</value> <!-- L -->
					<value>S</value> <!-- S -->
					<value>V</value> <!-- V -->
					<value>X</value> <!-- X -->
				</attr>
				<attr id="ACT" operator="in"> <!-- ACT - list type -->
					<value>N</value> <!-- N -->
					<value>C</value> <!-- C -->
					<value>D</value> <!-- D -->
					<value>T</value> <!-- T -->
					<value>M</value> <!-- M -->
				</attr>
			</optional>

			<prohibited
				error_message="'${attr}' should not be filled on '${form}'  cause &lt;br&gt; -  REQTYP (1) isn`t set to: E,L,M,S,V or X &lt;br&gt; -  ACT isn`t set to N,C,D,T or M">
				<otherwise />
			</prohibited>
		</validator>

		<validator name="1_PPTD" class="com.glpo.gateway.oc.GenericParameterValidator">
			<target_attributes>
				<id>PPTD</id> <!-- PPTD -->
			</target_attributes>

			<optional>				
				<attr id="PROJECT" operator="not empty" /> <!-- PROJECT -->
			</optional>

			<prohibited error_message="'${attr}' should not be filled on '${form}' cause &lt;br&gt; - the PROJECT not filled. ">
				<otherwise />
			</prohibited>
		</validator>

		<validator name="1_LUP" class="com.glpo.gateway.oc.GenericParameterValidator">
			<target_attributes>
				<id>LUP</id><!-- LUP -->
			</target_attributes>

			<optional>
				<otherwise />
			</optional>

			<prohibited error_message="'${attr}' should not be filled on '${form}' cause &lt;br&gt; - the PIU field should be filled.">
				<attr id="PIU" operator="empty" />
			</prohibited>

			<prohibited error_message="'${attr}' should not be filled on '${form}' cause &lt;br&gt; - the PIU field is 100.">
				<attr id="PIU" operator="in"><!-- PIU -->
					<value>100</value><!-- 100 -->
				</attr>
			</prohibited>

			<prohibited error_message="'${attr}' should not be filled on '${form}' cause &lt;br&gt; - 00the REQTYP(1) field is R.">
				<attr id="REQTYP" operator="in"><!-- REQTYP(1) -->
					<value>R</value><!-- R -->
				</attr>
			</prohibited>

			<prohibited error_message="'${attr}' should not be filled on '${form}'  cause &lt;br&gt; -  ACT field is D">
				<attr id="ACT" operator="in"><!-- ACT -->
					<value>D</value><!-- D -->
				</attr>
			</prohibited>
		</validator>
	</form>
</configuration>
